### ISSUE TITLE
http3 + socks5 proxy?

### ISSUE THREAD

**Issue by ezbik** [yurymuski/curl-http3#10]
I have a socks5 proxy that is UDP capable (https://gost.run) but this CURL can't use it for HTTP3.

```
gost -L :2324?udp=true
docker run -it --rm ymuski/curl-http3 curl -IL https://yurets.pro --http3 -x socks5h://aaa.bbb:2324 
```

```
HTTP/1.1 200 OK
```

**Comment by yurymuski** [comment]
@ezbik Hello, this repo is regular curl compiled with EXPERIMENTAL feature http3 =)

https://github.com/curl/curl/blob/master/docs/HTTP3.md#quiche-version

you can contribute or ask for socks5 proxy support there. https://github.com/curl/curl/issues

**Comment by ezbik** [comment]
**A workaround how to check QUIC with this curl, through a Socks5 proxy**

- extract `curl_quic` from Docker https://github.com/yurymuski/curl-http3/
- download `glider` from https://github.com/nadoo/glider (for making a tunnel)
- we have a socks5 server `socks5://alice:cool@localhost:5001`
- make a UDP tunnel through the socks5 proxy to the QUIC website (example: https://quic.tanatos.org:444/ ) (1)
- downloading a test file through the tunnel (2) 

1. `glider -verbose  -listen udp://:1444 -forward socks5://alice:cool@localhost:5001,udp://quic.tanatos.org:444`
2. `curl_quic --connect-to quic.tanatos.org:444:localhost:1444  --http3 https://quic.tanatos.org:444/file3m.txt -o /dev/null`
