### ISSUE TITLE
http2 support?

### ISSUE THREAD

**Issue by linuxd3v** [yurymuski/curl-http3#8]
> docker run -it --rm ymuski/curl-http3 curl --version                            
> curl 8.1.2-DEV (x86_64-pc-linux-gnu) libcurl/8.1.2-DEV BoringSSL quiche/0.17.2
> Release-Date: [unreleased]
> Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
> Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL threadsafe UnixSockets

  
HTTP2 is seemingly not listed. Also this version of curl seemingly doesn't work with http2.  Is this by design?

**Comment by yurymuski** [comment]
@linuxd3v  added and released new version

```
docker pull ymuski/curl-http3:latest
docker pull ymuski/curl-http3:8.2.1
```
